version: '2.4'

services:
  db:
    image: mariadb:10.6
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    volumes:
      - omekadb:/var/lib/mysql
    restart: unless-stopped
    environment: # the mysql user is 'root'
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka


  omeka:
    depends_on:
      db:
        condition: service_healthy
    image: fsg/omeka-s:as_user
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./modules/:/var/www/html/modules/
      - ./themes/:/var/www/html/themes/
    restart: unless-stopped

volumes:
  omekadb:
